server {
    listen 80;
    listen [::]:80;
    server_name bookmarks.aggregat4.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name bookmarks.aggregat4.net;

    include /etc/nginx/snippets/a4-tls.conf;
    access_log /var/log/nginx/bookmarks.access.log combined;

    location / {
        proxy_pass http://127.0.0.1:1302;
        include /etc/nginx/snippets/a4-proxy-headers.conf;
    }
}
